src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass=ImageRepository::class)
 * 
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $path;


    /**
     * @var UploadedFile
     * 
     * @Assert\Image(
     *  maxSize = "10"
     * )
     */
    private $file;

    /**
     * @var ?string
     */
    private $oldPath;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }

    /**
     * @return  self
     */ 
    public function setFile($file)
    {
        $this->file = $file;
        $this->oldPath = $this->path;
        $this->path = "";

        return $this;
    }

    /**
     */
    public function getPublicRootDir(): string
    {
        return __DIR__ . "../../../public/uploads/";
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function generatePath(): void 
    {
        if ($this->file instanceof UploadedFile) {
            $this->path = uniqid('img_').'.'.$this->file->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload(): void
    {
        if (is_file($this->getPublicRootDir().$this->oldPath)) {
            unlink($this->getPublicRootDir().$this->oldPath);
        }

        if ($this->file instanceof UploadedFile) {
            $this->file->move($this->getPublicRootDir(), $this->path);
        }
    }

    public function getWebPath(): string 
    {
        return '/uploads/'.$this->path;
    }

}

src/Entity/Objet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ObjetRepository;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ObjetRepository")
 */
class Objet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Marque;

    /**
     * @ORM\Column(type="float")
     */
    private $Prix;


    public function getImage(): ?Image
    {
        return $this->image;
    }

    /**
     * @ORM\OneToOne(targetEntity=Image::class, cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $image;

    /**
     * @ORM\ManyToMany(targetEntity=Categories::class, inversedBy="objets")
     */
    private $categories;

    /**
     * @ORM\ManyToOne(targetEntity=Panier::class, inversedBy="objets")
     */
    private $panier;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="objets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->Marque;
    }

    public function setMarque(?string $Marque): self
    {
        $this->Marque = $Marque;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    /**
     * @return Collection|Categories[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categories $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addObjet($this);
        }

        return $this;
    }

    public function removeCategory(Categories $category): self
    {
        if ($this->categories->removeElement($category)) {
            $category->removeObjet($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Nom;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(?Panier $panier): self
    {
        $this->panier = $panier;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/ObjetType.php
<?php

namespace App\Form;

use App\Entity\Categories;
use App\Entity\Objet;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Doctrine\ORM\EntityRepository;
use Knp\Menu\FactoryInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Security\Core\Security;

class ObjetType extends AbstractType
{

    private $security;

    public function __construct(Security $security /* private Security $security*/)
    {
        $this->security = $security; //PHP7
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        if ($this->security->isGranted('ROLE_USER')) {
            $builder
                ->add('Nom', null)
                ->add('Description', null)
                ->add('Marque')
                ->add('Prix')
                ->add('categories', EntityType::class, [
                    'class' => Categories::class,
                    'label' => 'Catégories de l\'objet',
                    'multiple' => true,
                ])
                ->add('image', ImageType::class, [
                    'required' => false,
                ])
            ;
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Objet::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/ObjetController.php
<?php

namespace App\Controller;

use App\Entity\Objet;
use App\Entity\Panier;
use App\Form\ObjetType;
use App\Repository\CategoriesRepository;
use App\Repository\ObjetRepository;
use App\Repository\PanierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[Route('/objet')]
class ObjetController extends AbstractController
{
    #[Route('/', name: 'objet_index', methods: ['GET'])]
    public function index(ObjetRepository $objetRepository, CategoriesRepository $categoriesRepository, Request $request): Response
    {
        $search =$request->get('s', '');

        return $this->render('objet/index.html.twig', [
            'objets' => $objetRepository->findSearch($search),
            'categoryList' => $categoriesRepository->findAll(),

        ]);
    }

    #[Route('/new', name: 'objet_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $user = $this->getUser();
        if (null === $user)
        {
            return $this->redirectToRoute('objet_index');
        }

        $objet = new Objet();
        $form = $this->createForm(ObjetType::class, $objet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $objet->setUser($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($objet);
            $entityManager->flush();

            return $this->redirectToRoute('objet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('objet/new.html.twig', [
            'objet' => $objet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'objet_show', methods: ['GET'])]
    public function show(Objet $objet): Response
    {
        return $this->render('objet/show.html.twig', [
            'objet' => $objet,
        ]);
    }

    #[Route('/{id}/edit', name: 'objet_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Objet $objet): Response
    {
        $user = $this->getUser();
        if ($objet->getUser() != $user)
        {
            return $this->redirectToRoute('objet_index');
        }

        $form = $this->createForm(ObjetType::class, $objet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('objet_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('objet/edit.html.twig', [
            'objet' => $objet,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'objet_delete', methods: ['POST'])]
    public function delete(Request $request, Objet $objet): Response
    {
        $user = $this->getUser();
        if ($objet->getUser() != $user)
        {
            return $this->redirectToRoute('objet_index');
        }

        if ($this->isCsrfTokenValid('delete'.$objet->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($objet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('objet_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/{id}/panier", requirements={"id":"\d+"})
     * @IsGranted("ROLE_USER")
     */
    public function add2Cart(Objet $entity, PanierRepository $panierRepository, EntityManagerInterface $entityManager, Request $request): Response
    {
        $user = $this->getUser();
        $panier = $panierRepository->findOne($user);

        if (null === $user)
        {
            return $this->redirectToRoute('objet_index');
        }
        if (null === $panier)
        {
            $panier = (new Panier)
                ->setUser($user)
                ->addObjet($entity)
            ;

            $entityManager->persist($panier);

        } else {
        $panier->addObjet($entity);
        }

        $entityManager->flush();

        return $this->redirectToRoute('objet_index');
    }

    /**
     * @Route("/{id}/removepanier", requirements={"id":"\d+"})
     * @IsGranted("ROLE_USER")
     */
    public function removeCart(Objet $entity, PanierRepository $panierRepository, EntityManagerInterface $entityManager, Request $request): Response
    {
        $user = $this->getUser();
        if (null === $user)
        {
            return $this->redirectToRoute('objet_index');
        }
        
        $user = $this->getUser();
        $panier = $panierRepository->findOne($user);

        if (null === $panier)
        {

        } else {
        $panier->removeObjet($entity);
        }

        $entityManager->flush();

        return $this->redirectToRoute('panier_show');
    }
}

templates/objet/_delete_form.html.twig
<form method="post" action="{{ path('objet_delete', {'id': objet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ objet.id) }}">
    <button class="btn btn-danger" style='margin-top:10px'>Supprimer</button>
</form>

templates/objet/_form.html.twig
{{ form_start(form) }} {# ouverture balise form #}

    <div class="card">  
        <div class="card-body"> 
            {% block formBody %}
                {{ form_widget(form) }} {# affiche les champs du formulaire #}  
            {% endblock %}
        </div>

        <div class="card-footer">
            {# button:submit.btn.btn-primary #}
            <button type="submit" class="btn btn-primary">Enregistrer</button>
        </div>

    </div>

{{ form_end(form) }} {# fermeture balise form #}

templates/objet/edit.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <h1 style="text-align : center">Editer un objet</h1><br>
    
    {{ include('objet/_form.html.twig', {'button_label': 'Editer'}) }}

    <a href="{{ path('objet_index') }}" class="btn btn-secondary" class="btn btn-secondary">Retour</a>
    {{ include('objet/_delete_form.html.twig') }}
    
{% endblock %}

templates/objet/index.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <style>
        p.solid {max-width: 300px; max-height:50px; overflow: hidden; text-overflow: ellipsis;}' 
    </style>

    <h1 style="text-align:center" >Trouvez votre bonheur...</h1> 
    <div class="d-flex justify-content-between align-items-center mb-3">
        <form action="" method='GET'>
                <div class="input-group mb-3">
                    <input id="rech" style="margin-left:10px" type="text" name="s" placeholder="Votre recherche" class="form-control" value = '{{ app.request.get("s", "") }}'>
                    <button id="rech" style="margin-left:10px" type="submit" class="btn btn-light">Rechercher</i></button>
                </div>
        </form>
    </div>
    
       <ul class="nav flex-column lightmode_nav" id="nav" style="float:left; margin:5px; padding:2px width:auto; border-radius:2%">
            <h6 class='nav-item'>Catégories</h6>
            <li class="nav-item"><a href="{{ path('objet_index') }}">Toutes</a></li>
            {% for cat in categoryList %}
            <li class="nav-item"><a href="{{ path('categories_show', {'id': cat.id}) }}">{{cat.nom}}</a></li>
            {% endfor %}
            <button onclick="switch_color()" class="lightmode_body" id="but" style="float:left; margin:5px; border-radius:5%;">THEME</button>
        </ul>
         <div class="nav flex-column  lightmode_container" id="container" style="width:auto; margin:5px; padding:10px; border-radius:2%; right:0px;">
            <div class="row">
            {% for objet in objets %}
                <div class="col-md-4">
                    {% if objet.image is not empty %}
                        <a href="{{ path('objet_show', {'id': objet.id}) }}"><img src="{{ asset(objet.image.webPath) }}" alt="{{ objet.Nom }}" style="max-width: 250px;max-height: 300px;"/></a>
                    {% endif %}
                    <br/>
                    <a href="{{ path('objet_show', {'id': objet.id}) }}"><b style="font-size:23px;">{{ objet.Nom }}</b></a>
                    <p class='solid'>{{ objet.Description }}</p>
                    Marque : <i>{{ objet.Marque }}</i> |  Catégorie : {% for category in objet.categories %} {{category.nom}} {% endfor %}
                    <p>{{ objet.Prix }}€</p>
                    <br/>
                </div>
            {% endfor %}
            </div>
        </div>   
{% endblock %}

templates/objet/new.html.twig
{% extends "base.html.twig" %}

{% block title %}New Object{% endblock %}

{% block content %}
    <h1 style="text-align: center">Créer un nouvel objet</h1>

    {% embed "decorator/_form.html.twig" %}
    {% endembed %}

    <a href="{{ path('objet_index') }}" class="btn btn-secondary">Retour</a>

   
{% endblock %}

templates/objet/show.html.twig
{% extends "base.html.twig" %}
{% block title %}{{objet.Nom}}{% endblock %}

{% block content %}
    <div class="nav flex-column lightmode_nav" id="nav" style="float:left; margin:5px; padding:2px width:auto; border-radius:2%">
        {% for category in objet.categories %}
            <span><a href="{{ path('objet_index') }}">Tout</a> > <a href="{{ path('categories_show', {'id': category.id}) }}">{{category.nom}} </a> </span>
        {% endfor %}
        <button onclick="switch_color()" class="lightmode_body" id="but" style="float:left; margin:5px; border-radius:5%; width:100px">THEME</button>
         {% if objet.image is not empty %}
            <a href="{{ path('objet_show', {'id': objet.id}) }}"><img class="img-fluid" src="{{ asset(objet.image.webPath) }}" alt="{{ objet.Nom }}" style="max-width: 500px; max-height:700px"/></a>
         {% endif %}
    </div>
    <div class="nav flex-column lightmode_nav" id="nav" style="margin:5px; padding:2px width:auto; border-radius:2%; right:0px;">
        <h2 class="display-3 text-center"> {{objet.Nom}} </h2>
        <br/><br/><br/>
        <p class="display-6"> Prix : <b>{{objet.Prix}}€</b> </p>
        <blockquote class="blockquote text-center">
        <p class="mb-0">{{ objet.Description }}</p>
        </blockquote>

        <table id="table" class="table table-light table-striped">
        <tbody>
            <tr>
                <th><h6 class="display-6">Informations sur l'objet :</h6></th>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ objet.Marque }}</td>
            </tr>
            <tr>
            <tr>
                <th>Categorie</th>
                <td>
                    {% for category in objet.categories %}
                        {{category.nom}} <br/>
                    {% endfor %}
                </td>
                
            </tr>
        </tbody>
    </table>

    <a class="btn btn-primary" style="width:250px" href="{{ path('app_objet_add2cart', {'id': objet.id}) }}">Ajouter au panier</a><br/>
    {% if app.user != null %}
        {% if objet.user == app.user %}
                <span style='text-align:right'><a class="btn btn-dark" style="width:100px" href="{{ path('objet_edit', {'id': objet.id}) }}">EDITER</a>
                {{ include('objet/_delete_form.html.twig') }}</span>
        {% endif %}
    {% endif %}
    </div>
{% endblock %}